# For more information, please refer to deployment documentation: https://github.com/finos/symphony-wdk/blob/master/docs/deployment.md
bdk:
  host: psdev.symphony.com
  bot:
    username: bot-customer-blast
    privateKey:
      path: rsa/privatekey.pem
