apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-customer-blast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-customer-blast
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: bot-customer-blast
    spec:
      volumes:
        - name: rsa-key
          secret:
            secretName: bot-customer-blast-private-key
      containers:
        - name: bot-customer-blast
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          volumeMounts:
            - name: rsa-key
              mountPath: "/rsa"
              readOnly: true